baseurl = "https://rejxcy.github.io/MyWebsite/"
title = "Roy's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "zh-tw"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/coffee.png"
  SEOTitle = "胡志龍"
  description = "胡志龍，iOS app 開發人員，一個軟體工程師"
  keyword = "胡志龍, Roy, roy, rejxcy, Roy Hu, Roy's Blog, roy's Blog, Roy's, roy's"
  slogan = "輕鬆生活，記錄歷程"

  image_404 = "img/404-bg.jpg"
  title_404 = "你怎麼來到這的，請告訴我 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "iOS App Developer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/think.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

 
  friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "rejxcy0903@gmail.com"
  linkedin       = "https://www.linkedin.com/in/%E5%BF%97%E9%BE%8D-%E8%83%A1-17b70a273/"
  stackoverflow  = "https://stackoverflow.com/users/21704431/rejxcy"
  github         = "https://github.com/rejxcy?tab=repositories"
  
  [[params.friend_link]]
  title = "jayson"
  href =  "https://jaysonliang.com/"

  [[params.friend_link]]
  title = "liyou"
  href =  "https://liyou-chen.site/"
 
  
  [[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
